config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'make_mentor', to: 'skills#make_mentor'

  resources :users do
    resources :skills, only: [:new, :create]
  end
  resources :skills
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :skills
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates_presence_of :title

  belongs_to :category
  has_many :user_skills, dependent: :destroy
  has_many :users, through: :user_skills

  def find_students
    users.distinct.where(id: UserSkill.where(skill_id: id, mentoring?: false).pluck(:user_id))
  end

  def find_mentors
    users.distinct.where(id: UserSkill.where(skill_id: id, mentoring?: true).pluck(:user_id))
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates_presence_of :password, require: true
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :city
  validates_presence_of :role

  has_many :user_skills
  has_many :skills, through: :user_skills

  enum role: ['default', 'admin']

  has_secure_password

  def skills_to_learn
    skills.distinct.where(id: UserSkill.where(user_id: id, mentoring?: false).pluck(:skill_id))
  end

  def skills_to_mentor
    skills.distinct.where(id: UserSkill.where(user_id: id, mentoring?: true).pluck(:skill_id))
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @skills = @category.skills
  end

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :require_admin, only: [:edit, :update, :destroy]

  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
    @students = @skill.find_students
    @mentors = @skill.find_mentors
  end

  def new
    if params[:user_id]
      @user_id = params[:user_id]
      @user_skill = UserSkill.new
    else
      @skill = Skill.new
    end
  end

  def create
    if params[:commit] == 'Add New Skill'
      skill_id = params[:user_skill][:skill_id]
      user = User.find(params[:user_id])
      UserSkill.create(user_id: user.id, skill_id: skill_id)
      redirect_to user_path(user)
    else
      skill = Skill.create(skill_params)
      redirect_to skill_path(skill)
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    skill = Skill.find(params[:id])
    skill.update(skill_params)
    redirect_to skill_path(skill)
  end

  def destroy
    skill = Skill.find(params[:id])
    skill.destroy
    redirect_to skills_path
  end

  private

  def skill_params
    params.require(:skill).permit(:title, :description, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :name, :email, :city, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit class:"btn btn-primary mb-2" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<header>
  <div>Edit Category</div>
</header>

<section class='edit-category-main'>
  <div class='edit-category-form'><%= render partial: 'form' %><div>
</section>

app/views/categories/index.html.erb
<header class='category-index-header'>
  <div>Categories</div>
</header>

<% if current_admin? %>
  <a class="btn btn-primary btn-lg btn-block" id='add-new-skill-button' href="<%= new_category_path %>">Create New Category</a>
<% end %>

<section class='category-index-main'>
  <% @categories.shuffle.each do |category| %>
    <div class='category-index-main-item'>
      <h4><%= link_to category.title, category_path(category) %></h4>
      <p><%= category.description %></p>
    </div>
  <% end %>
</section>

app/views/categories/new.html.erb
<header>
  <div>Create New Category</div>
</header>

<section class='new-category-main'>
  <div class='new-category-form'><%= render partial: 'form' %><div>
</section>

app/views/categories/show.html.erb
<header>
  <h1><%= @category.title %></h1>
  <h4><%= @category.description %></h4>
</header>

<% if current_admin? %>
  <div class="btn-group" id='category-show-buttons' role="group" aria-label="Basic example">
    <%= link_to "Delete", category_path(@category), class: "btn btn-secondary", id:'category-show-delete', method: 'delete', data: {confirm: "Really want to delete this category?"} %>
    <%= link_to "Edit", edit_category_path(@category), class: "btn btn-secondary", id:'category-show-edit', method: 'get' %>
  </div>
<% end %>

<section class='category-show-main'>
  <h3 id='category-show-main-header'>Skills</h3>
  <% @skills.shuffle.each do |skill| %>
    <div class='category-show-main-item'>
      <h4><%= link_to skill.title, skill_path(skill) %></h4>
      <p><%= skill.description %></p>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MentorMatcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mentor-nav" id='site-nav-bar'>
      <a href="<%= root_path %>"<div class='navbar-brand'>MentorMatcher</div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item active">
              <a class="nav-link" href="<%= user_path(current_user) %>"><%= current_user.name %><span class="sr-only">(current)</span></a>
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%= skills_path %>">Skills</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%= categories_path %>">Categories</a>
          </li>
        </ul>
        <% end %>
      </div>
      <% if current_user %>
        <a class="nav-item active nav-link" id='nav-logout-button' href="<%= logout_path %>">Logout<span class="sr-only">(current)</span></a>
      <% else %>
        <a class="nav-item active nav-link" id='nav-login-button' href="<%= login_path %>">Login<span class="sr-only">(current)</span></a>
      <% end %>
    </nav>
    <%= yield %>
  </body>
  <footer>
    <div>presented by Colin Armstrong</div>
  </footer>
</html>

app/views/skills/_form.html.erb
<%= form_for [@user, @skill] do |f| %>
  <div>
    <%= f.label 'Category' %>
    <%= f.collection_select :category_id, Category.order(:title), :id, :title, include_blank: true %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit class:"btn btn-primary mb-2" 'Add Skill'%>
  </div>
<% end %>

app/views/skills/edit.html.erb
<header>
  <div>Edit Skill</div>
</header>

<section class='edit-skill-main'>
  <div class="edit-skill-form">
    <%= render partial: 'form' %>
  </div>
</section>

app/views/skills/index.html.erb
<header>
  <div>Skills</div>
</header>

<% if current_admin? %>
  <a class="btn btn-primary btn-lg btn-block" id='add-new-skill-button' href="<%= new_skill_path %>">Create New Skill</a>
<% end %>

<section class='skill-index-main'>
  <% @skills.shuffle.each do |skill| %>
    <div class='skill-index-main-item'>
      <h4><%= link_to skill.title, skill_path(skill) %></h4>
      <p><%= skill.description %></p>
    </div>
  <% end %>
</section>

app/views/skills/new.html.erb
<% if @user_id %>
  <header>
    <div>Add New Skill</div>
  </header>

  <section id='new-user-skill-main'>
    <div id="new-user-skill-form">
      <%= form_for @user_skill do |f| %>
        <%= f.label 'New Skill' %>
        <%= f.collection_select :skill_id, Skill.order(:title), :id, :title, include_blank: true %>

        <%= f.label ' ' %>
        <%= f.hidden_field :user_id, :readonly => true %>

        <%= f.submit 'Add New Skill'%>
      <% end %>
    </div>
  </section>
<% else %>
  <header>
    <div>Create New Skill</div>
  </header>

  <section class='new-skill-main'>
    <div class="new-skill-form">
      <%= render partial: 'form' %>
    </div>
  </section>
<% end %>

app/views/skills/show.html.erb
<header>
  <h1><%= @skill.title %></h1>
  <h4><%= @skill.description %></h4>
</header>

<% if current_admin? %>
  <div class="btn-group" id='category-show-buttons' role="group" aria-label="Basic example">
    <%= link_to "Delete", skill_path(@skill), class: "btn btn-secondary", id:'category-show-delete', method: 'delete', data: {confirm: "Really want to delete this skill?"} %>
    <%= link_to "Edit", edit_skill_path(@skill), class: "btn btn-secondary", id:'category-show-edit', method: 'get' %>
  </div>
<% end %>

<div class='skill-category-link'>
  <h3><%= link_to "View more skills in the #{@skill.category.title} category", category_path(@skill.category) %></h3>
</div>

<section class='skill-show-main'>
  <div class='skill-show-main-left'>
    <h2 id='skills-to-learn-header'>Students</h2>
    <% @students.shuffle.each do |student| %>
      <div class='skill-show-skill'>
        <h4><%= link_to student.name, user_path(student) %></h4>
      </div>
    <% end %>
  </div>
  <div class='skill-show-main-right'>
    <h2 id='skills-to-mentor-header'>Mentors</h2>
    <% @mentors.shuffle.each do |mentor| %>
      <div class='skill-show-skill'>
        <h4><%= link_to mentor.name, user_path(mentor) %></h4>
      </div>
    <% end %>
  </div>
</section>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.submit class:"btn btn-primary mb-2" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<header>
  <div>Create Your Account</div>
</header>


<section class='new-user-main'>
  <div class="new-user-form">
    <%= render partial: 'form' %>
  </div>
</section>

app/views/users/show.html.erb
<% if @user.id == current_user.id  %>
  <header>
    <h1>Welcome, <%= @user.name %></h1>
  </header>
<% else %>
  <header>
    <h1>Viewing <%= @user.name %>'s profile</h1>
  </header>
<% end %>

<% if @user.id == current_user.id || current_admin? %>
  <a class="btn btn-primary btn-lg btn-block" id='add-new-skill-button' href="<%= new_user_skill_path(@user) %>">Add New Skill</a>
<% end %>

<section class='user-info'>
  <h4>Phone Number: <%= @user.phone_number %></h4>
  <h4> | </h4>
  <h4>City: <%= @user.city %></h4>
  <h4> | </h4>
  <h4>Email: <%= @user.email %></h4>
</section>

<section class='user-show-main'>
  <div class='user-show-main-left'>
    <h2 id='skills-to-learn-header'>Skills <%= @user.name %> Wants to Learn</h2>
    <% @user.skills_to_learn.shuffle.each do |skill| %>
      <div class='user-show-skill'>
        <h4><%= link_to skill.title, skill_path(skill) %></h4>
        <p><%= skill.description %></p>
      </div>
    <% end %>
  </div>
  <div class='user-show-main-right'>
    <h2 id='skills-to-mentor-header'>Skills <%= @user.name %> Wants to Mentor</h2>
    <% @user.skills_to_mentor.shuffle.each do |skill| %>
      <div class='user-show-skill'>
        <h4><%= link_to skill.title, skill_path(skill) %></h4>
        <p><%= skill.description %></p>
      </div>
    <% end %>
  </div>
</section>

app/views/welcome/index.html.erb
<header class='category-index-header'>
  <div>Welcome to MentorMatcher!</div>
</header>

<section class='welcome-page-main'>
  <a class="btn btn-info " id='signup-button' href="<%= new_user_path %>">Sign Up to be a New User</a>
  <a class="btn btn-success" id='initial-login-button' href="<%= login_path %>">I already have an account</a>
</section>